apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  serviceName: minio
  replicas: 2
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      hostNetwork: true
      subdomain: minio
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: s3
        nfs:
          path: "/minio"
          server: 169.254.169.254
      containers:
      - name: minio
        env:
        - name: MINIO_STORAGE_CLASS_STANDARD
          value: "EC:2"
        - name: MINIO_STORAGE_CLASS_RRS
          value: "EC:2"
        - name: MINIO_ACCESS_KEY
          value: "minio-sample"
        - name: MINIO_SECRET_KEY
          value: "minio-sample-key"
        image: minio/minio:RELEASE.2019-06-13T01-41-13Z
        args:
        - server
        - --address
        - :9001
        - http://minio-0.minio.default.svc.cluster.local/minio/1
        - http://minio-0.minio.default.svc.cluster.local/minio/2
        - http://minio-0.minio.default.svc.cluster.local/minio/3
        - http://minio-0.minio.default.svc.cluster.local/minio/4
        - http://minio-1.minio.default.svc.cluster.local/minio/1
        - http://minio-1.minio.default.svc.cluster.local/minio/2
        - http://minio-1.minio.default.svc.cluster.local/minio/3
        - http://minio-1.minio.default.svc.cluster.local/minio/4
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: s3
          mountPath: /minio
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  clusterIP: None
  ports:
  - port: 9000
    name: minio
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-ui
  annotations:
    external-dns.alpha.kubernetes.io/hostname: minio.fuzzybunny.internal
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
  selector:
    app: minio