kind: Pod
apiVersion: v1
metadata:
  name: minio-b
spec:
  hostNetwork: true
  subdomain: minio-b
  volumes:
  - name: s3
    hostPath:
      path: "/s3"
  containers:
  - name: minio-b
    env:
    - name: MINIO_ACCESS_KEY
      value: "minio-b"
    - name: MINIO_SECRET_KEY
      value: "minio-b-key"
    image: minio/minio:RELEASE.2019-08-01T22-18-54Z
    args:
    - server
    - --address
    - :9001
    - http://192.168.127.251:9001/s3/minio-b00/vol
    - http://192.168.127.251:9001/s3/minio-b01/vol
    - http://192.168.127.252:9001/s3/minio-b02/vol
    - http://192.168.127.252:9001/s3/minio-b03/vol
    ports:
    - containerPort: 9001
    volumeMounts:
    - name: s3
      mountPath: /s3
    livenessProbe:
      httpGet:
        path: /minio/health/live
        port: 9001
      initialDelaySeconds: 120
      periodSeconds: 20
