---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: transmission
  template:
    metadata:
      labels:
        k8s-app: transmission
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      volumes:
      - name: transmission-data
        persistentVolumeClaim:
          claimName: transmission-pvc
      initContainers:
      - name: nftables
        image: randomcoww/nftables:20190119.01
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        env:
        - name: NFTABLES_LOCAL_CONFIG
          value: |
            table ip filter {
              chain output {
                type filter hook output priority 30; policy drop;
                ct state { established, related } accept
                oifname "tun*" accept
                skgid { "nobody" } accept
                ip daddr { 192.168.0.0/16, 10.0.0.0/8, 169.254.0.0/16 } accept
              }
            }
            ;

      containers:
      - name: openvpn
        image: randomcoww/openvpn:20190819.02
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        env:
        - name: PIA_PROFILE
          value: "US Seattle"
        - name: OVPN_AUTH_USER_PASS
          valueFrom:
            secretKeyRef:
              name: openvpn-auth-user-pass
              key: openvpn-auth-user-pass
        args:
        - "--config \"$(PIA_PROFILE).ovpn\""
        - "--route 192.168.0.0 255.255.0.0 net_gateway"
        - "--route 10.0.0.0 255.0.0.0 net_gateway"
        - "--route-nopull"
        - "--redirect-gateway"
        - "--fast-io"
        - "--auth-nocache"
      - name: mover
        image: busybox:latest
        args:
        - sleep
        - "1000000"
        volumeMounts:
        - name: transmission-data
          mountPath: "/transmission"
      - name: transmission
        image: randomcoww/transmission:20190819.02
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        ports:
        - containerPort: 9091
        volumeMounts:
        - name: transmission-data
          mountPath: "/var/lib/transmission"
        env:
        - name: TRANSMISSION_LOCAL_CONFIG
          value: |-
            {
              "alt-speed-down": 1900,
              "alt-speed-enabled": true,
              "alt-speed-time-begin": 540,
              "alt-speed-time-day": 127,
              "alt-speed-time-enabled": false,
              "alt-speed-time-end": 1020,
              "alt-speed-up": 10,
              "bind-address-ipv4": "0.0.0.0",
              "bind-address-ipv6": "::",
              "blocklist-enabled": false,
              "blocklist-url": "http://www.example.com/blocklist",
              "cache-size-mb": 4,
              "dht-enabled": true,
              "download-dir": "/var/lib/transmission/downloads",
              "download-limit": 100,
              "download-limit-enabled": 0,
              "download-queue-enabled": true,
              "download-queue-size": 5,
              "encryption": 1,
              "idle-seeding-limit": 30,
              "idle-seeding-limit-enabled": false,
              "incomplete-dir": "/var/lib/transmission/incomplete",
              "incomplete-dir-enabled": true,
              "lpd-enabled": false,
              "max-peers-global": 200,
              "message-level": 1,
              "peer-congestion-algorithm": "",
              "peer-id-ttl-hours": 6,
              "peer-limit-global": 34919,
              "peer-limit-per-torrent": 16959,
              "peer-port": 51413,
              "peer-port-random-high": 65535,
              "peer-port-random-low": 49152,
              "peer-port-random-on-start": false,
              "peer-socket-tos": "default",
              "pex-enabled": true,
              "port-forwarding-enabled": false,
              "preallocation": 1,
              "prefetch-enabled": true,
              "queue-stalled-enabled": true,
              "queue-stalled-minutes": 30,
              "ratio-limit": 0,
              "ratio-limit-enabled": true,
              "rename-partial-files": true,
              "rpc-authentication-required": false,
              "rpc-bind-address": "0.0.0.0",
              "rpc-enabled": true,
              "rpc-port": 9091,
              "rpc-url": "/transmission/",
              "rpc-username": "transmission",
              "rpc-whitelist": "127.0.0.1",
              "rpc-whitelist-enabled": false,
              "rpc-host-whitelist": "*.internal",
              "scrape-paused-torrents-enabled": true,
              "script-torrent-done-enabled": false,
              "script-torrent-done-filename": "",
              "seed-queue-enabled": false,
              "seed-queue-size": 10,
              "speed-limit-down": 100,
              "speed-limit-down-enabled": false,
              "speed-limit-up": 100,
              "speed-limit-up-enabled": false,
              "start-added-torrents": false,
              "trash-original-torrent-files": false,
              "umask": 18,
              "upload-limit": 100,
              "upload-limit-enabled": 0,
              "upload-slots-per-torrent": 14,
              "utp-enabled": true,
              "watch-dir-enabled": false
            }
---
kind: Service
apiVersion: v1
metadata:
  name: transmission
  annotations:
    external-dns.alpha.kubernetes.io/hostname: tr.fuzzybunny.internal
spec:
  type: LoadBalancer
  ports:
  - name: webui
    port: 80
    targetPort: 9091
  selector:
    k8s-app: transmission
