apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound-config
  labels:
      addonmanager.kubernetes.io/mode: EnsureExists
data:
  00-configmap.conf: |
    server:
      interface-automatic: yes
      port: 53
      interface: 0.0.0.0
      num-threads: 2
      do-ip6: no
      do-udp: yes
      do-tcp: yes
      access-control: 0.0.0.0/0 allow
      do-not-query-localhost: no
    forward-zone:
      name: "."
      forward-tls-upstream: yes
      forward-addr: 9.9.9.9@853
    remote-control:
      control-enable: yes
---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: unbound
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: unbound
  template:
    metadata:
      labels:
        k8s-app: unbound
    spec:
      dnsPolicy: Default
      restartPolicy: Always
      containers:
      - name: unbound
        image: randomcoww/unbound:20180913.01
        volumeMounts:
        - name: config-volume
          mountPath: /etc/unbound/unbound.conf.d
      volumes:
      - name: config-volume
        configMap:
          name: unbound-config

---
kind: Service
apiVersion: v1
metadata:
  name: unbound-tcp-service
  annotations:
    metallb.universe.tf/allow-shared-ip: unbound
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.127.254
  ports:
  - name: default
    port: 53
    targetPort: 53
  selector:
    k8s-app: unbound

---
kind: Service
apiVersion: v1
metadata:
  name: unbound-udp-service
  annotations:
    metallb.universe.tf/allow-shared-ip: unbound
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.127.254
  ports:
  - name: default
    port: 53
    targetPort: 53
    protocol: UDP
  selector:
    k8s-app: unbound
