---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-tgt-config
data:
  config.json: |
    {
      "storages": [
        {
          "deviceID": 1000,
          "path": "file:/unifi/file",
          "online": true
        }
      ],
      "iscsiportals": [
        {
          "id": 0,
          "portal": "127.0.0.1:3260"
        }
      ],
      "iscsitargets": {
        "iqn.2016-09.com.gotgt.gostor:unifi": {
          "tpgts": {
            "1": [
              0
            ]
          },
          "luns": {
            "0": 1000
          }
        }
      }
    }

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: unifi-tgt
spec:
  selector:
    matchLabels:
      app: unifi-tgt
  template:
    metadata:
      labels:
        app: unifi-tgt
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: tgt-config
        configMap:
          name: unifi-tgt-config
      - name: unifi
        emptyDir: {}

      containers:
      - name: gotgt
        image: randomcoww/gotgt:20190815.01
        args:
        - daemon
        volumeMounts:
        - name: tgt-config
          mountPath: /root/.gotgt
        - name: unifi
          mountPath: /unifi
          mountPropagation: HostToContainer
        ports:
        - containerPort: 3260

      - name: s3backer
        securityContext:
          privileged: true
        image: randomcoww/s3backer:1.5.2
        args:
        - -d
        - --accessId=minio-b
        - --accessKey=minio-b-key
        - --baseURL=http://minio-b-ui.default.svc.cluster.local/
        - --blockSize=128k 
        - --size=2g
        - --listBlocks
        - --force
        - unifi-block
        - /unifi
        volumeMounts:
        - name: unifi
          mountPath: /unifi
          mountPropagation: Bidirectional
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: unifi-tgt
  iscsi:
    targetPortal: 127.0.0.1:3260
    iqn: iqn.2016-09.com.gotgt.gostor:unifi
    lun: 0
    fsType: 'ext4'
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: unifi-tgt
  resources:
    requests:
      storage: 2Gi